## Practica Diana Ospina LLM
## primer motor del proyecto: correos anonimizados + clasificación + semáforo + prioridad.

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [6]:
import pandas as pd

# Cargar archivo

ruta = "/content/drive/MyDrive/KeepCoding/AI_Escalation_Assistant/escalamientos_anonimizado.xlsx"
df = pd.read_excel(
    ruta,
    sheet_name="escalamiento",
    header=None
)

# La primera fila contiene los encabezados
df.columns = df.iloc[0]

# Eliminar la fila de encabezados repetida
df = df[1:]

# Reiniciar índices
df = df.reset_index(drop=True)

print(df.columns)
print(df.head())

Index(['Column1', 'Column2', 'Column3', 'Column4', 'Column5', 'Column6',
       'Column7', 'Column8', 'Column9', 'Column10', 'Column11', 'Column12',
       'Column13', 'Column14', 'Column15', 'Column16', 'Column17', 'Column18',
       'Column19'],
      dtype='object', name=0)
0                                            Column1  \
0                                             Asunto
1  Re: Solicitud puntos Porto Horizonte / EDIFICI...
2  Re: Urgente - Solicitud Cambio Asesor Comercia...
3                    Re: TRASLADO SERVICIOS INTELCIA
4                    RE: TRASLADO SERVICIOS INTELCIA

0                                            Column2                  Column3  \
0                                             Cuerpo             De: (nombre)
1  Cordial saludo:_x000D_\nSres. EDIFICIO PORTO H...  Claro Empresas Colombia
2  Cordial saludo Orlando,_x000D_\n_x000D_\n _x00...  Claro Empresas Colombia
3  Cordial saludo,_x000D_\n_x000D_\n _x000D_\n_x0...  Claro Empresas Colombia
4  Cordial saludo,_x000D_\n_x000D_\n _x000D_\n_x0...  Claro Empresas Colombia

0                                            Column4     Column5  \
0                                    De: (dirección)  De: (tipo)
1  /O=EXCHANGELABS/OU=EXCHANGE ADMINISTRATIVE GRO...          EX
2  /O=EXCHANGELABS/OU=EXCHANGE ADMINISTRATIVE GRO...          EX
3  /O=EXCHANGELABS/OU=EXCHANGE ADMINISTRATIVE GRO...          EX
4  /O=EXCHANGELABS/OU=EXCHANGE ADMINISTRATIVE GRO...          EX

0                                    Column6  \
0                             Para: (nombre)
1  Coordinador de Tecnologia Porto Horizonte
2              Orlando Alberto Suarez Robles
3                 Diana Isela Ospina Salazar
4                         Viviana Duque Soto

0                                            Column7       Column8  \
0                                  Para: (dirección)  Para: (tipo)
1                     ticportohorizonte@oxohotel.com          SMTP
2  /o=ExchangeLabs/ou=Exchange Administrative Gro...            EX
3  /o=ExchangeLabs/ou=Exchange Administrative Gro...            EX
4  /o=ExchangeLabs/ou=Exchange Administrative Gro...            EX

0                                            Column9  \
0                                       CC: (nombre)
1  Julian Heredia;Nicolas Felipe Guerra Lopez;Adm...
2  Juan Gonzalez;astrid.rodriguez@canpack.com;Dia...
3      Claudia Andrea Rios Patiño;Viviana Duque Soto
4  Diana Isela Ospina Salazar;Jenny Jimenez Gonza...

0                                           Column10  \
0                                    CC: (dirección)
1  jheredia@oxohotel.com;/o=ExchangeLabs/ou=Excha...
2  juan.gonzalez2@canpack.com;astrid.rodriguez@ca...
3  /o=ExchangeLabs/ou=Exchange Administrative Gro...
4  /o=ExchangeLabs/ou=Exchange Administrative Gro...

0                      Column11       Column12          Column13     Column14  \
0                    CC: (tipo)  CCO: (nombre)  CCO: (dirección)  CCO: (tipo)
1  SMTP;EX;SMTP;EX;SMTP;EX;SMTP            NaN               NaN          NaN
2                  SMTP;SMTP;EX            NaN               NaN          NaN
3                         EX;EX            NaN               NaN          NaN
4                 EX;EX;EX;SMTP            NaN               NaN          NaN

0  Column15    Column16     Column17     Column18     Column19
0  Carácter  Categorías  Facturación  Importancia  Kilometraje
1    Normal         NaN          NaN       Normal          NaN
2    Normal         NaN          NaN       Normal          NaN
3    Normal         NaN          NaN       Normal          NaN
4    Normal         NaN          NaN       Normal          NaN

In [8]:
for col in df.columns:
    print(col)

Column1
Column2
Column3
Column4
Column5
Column6
Column7
Column8
Column9
Column10
Column11
Column12
Column13
Column14
Column15
Column16
Column17
Column18
Column19

In [10]:
for i, col in enumerate(df.columns):
    print(i, "->", col)

0 -> Column1
1 -> Column2
2 -> Column3
3 -> Column4
4 -> Column5
5 -> Column6
6 -> Column7
7 -> Column8
8 -> Column9
9 -> Column10
10 -> Column11
11 -> Column12
12 -> Column13
13 -> Column14
14 -> Column15
15 -> Column16
16 -> Column17
17 -> Column18
18 -> Column19

In [11]:
for i in range(5):
    print(f"\nFILA {i}")
    print(df.iloc[i])

FILA 0
0
Column1                Asunto
Column2                Cuerpo
Column3          De: (nombre)
Column4       De: (dirección)
Column5            De: (tipo)
Column6        Para: (nombre)
Column7     Para: (dirección)
Column8          Para: (tipo)
Column9          CC: (nombre)
Column10      CC: (dirección)
Column11           CC: (tipo)
Column12        CCO: (nombre)
Column13     CCO: (dirección)
Column14          CCO: (tipo)
Column15             Carácter
Column16           Categorías
Column17          Facturación
Column18          Importancia
Column19          Kilometraje
Name: 0, dtype: object

FILA 1
0
Column1     Re: Solicitud puntos Porto Horizonte / EDIFICI...
Column2     Cordial saludo:_x000D_\nSres. EDIFICIO PORTO H...
Column3                               Claro Empresas Colombia
Column4     /O=EXCHANGELABS/OU=EXCHANGE ADMINISTRATIVE GRO...
Column5                                                    EX
Column6             Coordinador de Tecnologia Porto Horizonte
Column7                        ticportohorizonte@oxohotel.com
Column8                                                  SMTP
Column9     Julian Heredia;Nicolas Felipe Guerra Lopez;Adm...
Column10    jheredia@oxohotel.com;/o=ExchangeLabs/ou=Excha...
Column11                         SMTP;EX;SMTP;EX;SMTP;EX;SMTP
Column12                                                  NaN
Column13                                                  NaN
Column14                                                  NaN
Column15                                               Normal
Column16                                                  NaN
Column17                                                  NaN
Column18                                               Normal
Column19                                                  NaN
Name: 1, dtype: object

FILA 2
0
Column1     Re: Urgente - Solicitud Cambio Asesor Comercia...
Column2     Cordial saludo Orlando,_x000D_\n_x000D_\n _x00...
Column3                               Claro Empresas Colombia
Column4     /O=EXCHANGELABS/OU=EXCHANGE ADMINISTRATIVE GRO...
Column5                                                    EX
Column6                         Orlando Alberto Suarez Robles
Column7     /o=ExchangeLabs/ou=Exchange Administrative Gro...
Column8                                                    EX
Column9     Juan Gonzalez;astrid.rodriguez@canpack.com;Dia...
Column10    juan.gonzalez2@canpack.com;astrid.rodriguez@ca...
Column11                                         SMTP;SMTP;EX
Column12                                                  NaN
Column13                                                  NaN
Column14                                                  NaN
Column15                                               Normal
Column16                                                  NaN
Column17                                                  NaN
Column18                                               Normal
Column19                                                  NaN
Name: 2, dtype: object

FILA 3
0
Column1                       Re: TRASLADO SERVICIOS INTELCIA
Column2     Cordial saludo,_x000D_\n_x000D_\n _x000D_\n_x0...
Column3                               Claro Empresas Colombia
Column4     /O=EXCHANGELABS/OU=EXCHANGE ADMINISTRATIVE GRO...
Column5                                                    EX
Column6                            Diana Isela Ospina Salazar
Column7     /o=ExchangeLabs/ou=Exchange Administrative Gro...
Column8                                                    EX
Column9         Claudia Andrea Rios Patiño;Viviana Duque Soto
Column10    /o=ExchangeLabs/ou=Exchange Administrative Gro...
Column11                                                EX;EX
Column12                                                  NaN
Column13                                                  NaN
Column14                                                  NaN
Column15                                               Normal
Column16                                                  NaN
Column17                                                  NaN
Column18                                               Normal
Column19                                                  NaN
Name: 3, dtype: object

FILA 4
0
Column1                       RE: TRASLADO SERVICIOS INTELCIA
Column2     Cordial saludo,_x000D_\n_x000D_\n _x000D_\n_x0...
Column3                               Claro Empresas Colombia
Column4     /O=EXCHANGELABS/OU=EXCHANGE ADMINISTRATIVE GRO...
Column5                                                    EX
Column6                                    Viviana Duque Soto
Column7     /o=ExchangeLabs/ou=Exchange Administrative Gro...
Column8                                                    EX
Column9     Diana Isela Ospina Salazar;Jenny Jimenez Gonza...
Column10    /o=ExchangeLabs/ou=Exchange Administrative Gro...
Column11                                        EX;EX;EX;SMTP
Column12                                                  NaN
Column13                                                  NaN
Column14                                                  NaN
Column15                                               Normal
Column16                                                  NaN
Column17                                                  NaN
Column18                                               Normal
Column19                                                  NaN
Name: 4, dtype: object

In [12]:
# Usar la fila 0 como encabezados
df.columns = df.iloc[0]

# Eliminar la fila 0 porque ya quedó como encabezado
df = df.iloc[1:]

# Reiniciar índices
df = df.reset_index(drop=True)

# Verificar
print(df.columns)
df.head()

Index(['Asunto', 'Cuerpo', 'De: (nombre)', 'De: (dirección)', 'De: (tipo)',
       'Para: (nombre)', 'Para: (dirección)', 'Para: (tipo)', 'CC: (nombre)',
       'CC: (dirección)', 'CC: (tipo)', 'CCO: (nombre)', 'CCO: (dirección)',
       'CCO: (tipo)', 'Carácter', 'Categorías', 'Facturación', 'Importancia',
       'Kilometraje'],
      dtype='object', name=0)

,Asunto,Cuerpo,De: (nombre),De: (dirección),De: (tipo),Para: (nombre),Para: (dirección),Para: (tipo),CC: (nombre),CC: (dirección),CC: (tipo),CCO: (nombre),CCO: (dirección),CCO: (tipo),Carácter,Categorías,Facturación,Importancia,Kilometraje
0,Re: Solicitud puntos Porto Horizonte / EDIFICI...,Cordial saludo:_x000D_\nSres. EDIFICIO PORTO H...,Claro Empresas Colombia,/O=EXCHANGELABS/OU=EXCHANGE ADMINISTRATIVE GRO...,EX,Coordinador de Tecnologia Porto Horizonte,ticportohorizonte@oxohotel.com,SMTP,Julian Heredia;Nicolas Felipe Guerra Lopez;Adm...,jheredia@oxohotel.com;/o=ExchangeLabs/ou=Excha...,SMTP;EX;SMTP;EX;SMTP;EX;SMTP,NaN,NaN,NaN,Normal,NaN,NaN,Normal,NaN
1,Re: Urgente - Solicitud Cambio Asesor Comercia...,"Cordial saludo Orlando,_x000D_\n_x000D_\n _x00...",Claro Empresas Colombia,/O=EXCHANGELABS/OU=EXCHANGE ADMINISTRATIVE GRO...,EX,Orlando Alberto Suarez Robles,/o=ExchangeLabs/ou=Exchange Administrative Gro...,EX,Juan Gonzalez;astrid.rodriguez@canpack.com;Dia...,juan.gonzalez2@canpack.com;astrid.rodriguez@ca...,SMTP;SMTP;EX,NaN,NaN,NaN,Normal,NaN,NaN,Normal,NaN
2,Re: TRASLADO SERVICIOS INTELCIA,"Cordial saludo,_x000D_\n_x000D_\n _x000D_\n_x0...",Claro Empresas Colombia,/O=EXCHANGELABS/OU=EXCHANGE ADMINISTRATIVE GRO...,EX,Diana Isela Ospina Salazar,/o=ExchangeLabs/ou=Exchange Administrative Gro...,EX,Claudia Andrea Rios Patiño;Viviana Duque Soto,/o=ExchangeLabs/ou=Exchange Administrative Gro...,EX;EX,NaN,NaN,NaN,Normal,NaN,NaN,Normal,NaN
3,RE: TRASLADO SERVICIOS INTELCIA,"Cordial saludo,_x000D_\n_x000D_\n _x000D_\n_x0...",Claro Empresas Colombia,/O=EXCHANGELABS/OU=EXCHANGE ADMINISTRATIVE GRO...,EX,Viviana Duque Soto,/o=ExchangeLabs/ou=Exchange Administrative Gro...,EX,Diana Isela Ospina Salazar;Jenny Jimenez Gonza...,/o=ExchangeLabs/ou=Exchange Administrative Gro...,EX;EX;EX;SMTP,NaN,NaN,NaN,Normal,NaN,NaN,Normal,NaN
4,RE: Datos servicio Hogar para traslado a cuent...,"Cordial saludo Marvic,_x000D_\n_x000D_\n _x000...",Claro Empresas Colombia,/O=EXCHANGELABS/OU=EXCHANGE ADMINISTRATIVE GRO...,EX,Marvic Alexander Guerra Fuentes,/o=ExchangeLabs/ou=Exchange Administrative Gro...,EX,Diana Isela Ospina Salazar;auxiliar.administra...,/o=ExchangeLabs/ou=Exchange Administrative Gro...,EX;SMTP,NaN,NaN,NaN,Normal,NaN,NaN,Normal,NaN

In [13]:
for i, col in enumerate(df.columns):
    print(i, "->", col)

0 -> Asunto
1 -> Cuerpo
2 -> De: (nombre)
3 -> De: (dirección)
4 -> De: (tipo)
5 -> Para: (nombre)
6 -> Para: (dirección)
7 -> Para: (tipo)
8 -> CC: (nombre)
9 -> CC: (dirección)
10 -> CC: (tipo)
11 -> CCO: (nombre)
12 -> CCO: (dirección)
13 -> CCO: (tipo)
14 -> Carácter
15 -> Categorías
16 -> Facturación
17 -> Importancia
18 -> Kilometraje

In [14]:
# Seleccionar solo columnas útiles

columnas_utiles = [
    'Asunto',
    'Cuerpo',
    'De: (nombre)',
    'De: (dirección)',
    'Para: (nombre)',
    'Para: (dirección)'
]

df = df[columnas_utiles]

print(df.shape)
df.head()

(46, 6)

,Asunto,Cuerpo,De: (nombre),De: (dirección),Para: (nombre),Para: (dirección)
0,Re: Solicitud puntos Porto Horizonte / EDIFICI...,Cordial saludo:_x000D_\nSres. EDIFICIO PORTO H...,Claro Empresas Colombia,/O=EXCHANGELABS/OU=EXCHANGE ADMINISTRATIVE GRO...,Coordinador de Tecnologia Porto Horizonte,ticportohorizonte@oxohotel.com
1,Re: Urgente - Solicitud Cambio Asesor Comercia...,"Cordial saludo Orlando,_x000D_\n_x000D_\n _x00...",Claro Empresas Colombia,/O=EXCHANGELABS/OU=EXCHANGE ADMINISTRATIVE GRO...,Orlando Alberto Suarez Robles,/o=ExchangeLabs/ou=Exchange Administrative Gro...
2,Re: TRASLADO SERVICIOS INTELCIA,"Cordial saludo,_x000D_\n_x000D_\n _x000D_\n_x0...",Claro Empresas Colombia,/O=EXCHANGELABS/OU=EXCHANGE ADMINISTRATIVE GRO...,Diana Isela Ospina Salazar,/o=ExchangeLabs/ou=Exchange Administrative Gro...
3,RE: TRASLADO SERVICIOS INTELCIA,"Cordial saludo,_x000D_\n_x000D_\n _x000D_\n_x0...",Claro Empresas Colombia,/O=EXCHANGELABS/OU=EXCHANGE ADMINISTRATIVE GRO...,Viviana Duque Soto,/o=ExchangeLabs/ou=Exchange Administrative Gro...
4,RE: Datos servicio Hogar para traslado a cuent...,"Cordial saludo Marvic,_x000D_\n_x000D_\n _x000...",Claro Empresas Colombia,/O=EXCHANGELABS/OU=EXCHANGE ADMINISTRATIVE GRO...,Marvic Alexander Guerra Fuentes,/o=ExchangeLabs/ou=Exchange Administrative Gro...

In [15]:
import re
import pandas as pd

def anonimizar_texto(texto):

    if pd.isna(texto):
        return texto

    texto = str(texto)

    # Correos electrónicos
    texto = re.sub(
        r'[\w\.-]+@[\w\.-]+',
        '[EMAIL]',
        texto
    )

    # NIT aproximado
    texto = re.sub(
        r'\b\d{8,12}\b',
        '[NIT]',
        texto
    )

    # Teléfonos
    texto = re.sub(
        r'\b\d{7,10}\b',
        '[TELEFONO]',
        texto
    )

    # Órdenes de trabajo OT
    texto = re.sub(
        r'OT[\s:-]*\d+',
        '[OT]',
        texto,
        flags=re.IGNORECASE
    )

    return texto

In [16]:
columnas_anon = [
    'Asunto',
    'Cuerpo',
    'De: (nombre)',
    'Para: (nombre)'
]

for col in columnas_anon:
    df[col] = df[col].apply(anonimizar_texto)

In [17]:
df.head()

,Asunto,Cuerpo,De: (nombre),De: (dirección),Para: (nombre),Para: (dirección)
0,Re: Solicitud puntos Porto Horizonte / EDIFICI...,Cordial saludo:_x000D_\nSres. EDIFICIO PORTO H...,Claro Empresas Colombia,/O=EXCHANGELABS/OU=EXCHANGE ADMINISTRATIVE GRO...,Coordinador de Tecnologia Porto Horizonte,ticportohorizonte@oxohotel.com
1,Re: Urgente - Solicitud Cambio Asesor Comercia...,"Cordial saludo Orlando,_x000D_\n_x000D_\n _x00...",Claro Empresas Colombia,/O=EXCHANGELABS/OU=EXCHANGE ADMINISTRATIVE GRO...,Orlando Alberto Suarez Robles,/o=ExchangeLabs/ou=Exchange Administrative Gro...
2,Re: TRASLADO SERVICIOS INTELCIA,"Cordial saludo,_x000D_\n_x000D_\n _x000D_\n_x0...",Claro Empresas Colombia,/O=EXCHANGELABS/OU=EXCHANGE ADMINISTRATIVE GRO...,Diana Isela Ospina Salazar,/o=ExchangeLabs/ou=Exchange Administrative Gro...
3,RE: TRASLADO SERVICIOS INTELCIA,"Cordial saludo,_x000D_\n_x000D_\n _x000D_\n_x0...",Claro Empresas Colombia,/O=EXCHANGELABS/OU=EXCHANGE ADMINISTRATIVE GRO...,Viviana Duque Soto,/o=ExchangeLabs/ou=Exchange Administrative Gro...
4,RE: Datos servicio Hogar para traslado a cuent...,"Cordial saludo Marvic,_x000D_\n_x000D_\n _x000...",Claro Empresas Colombia,/O=EXCHANGELABS/OU=EXCHANGE ADMINISTRATIVE GRO...,Marvic Alexander Guerra Fuentes,/o=ExchangeLabs/ou=Exchange Administrative Gro...

In [18]:
columnas_anon = [
    'Asunto',
    'Cuerpo',
    'De: (nombre)',
    'De: (dirección)',
    'Para: (nombre)',
    'Para: (dirección)'
]

for col in columnas_anon:
    df[col] = df[col].apply(anonimizar_texto)

df.head()

,Asunto,Cuerpo,De: (nombre),De: (dirección),Para: (nombre),Para: (dirección)
0,Re: Solicitud puntos Porto Horizonte / EDIFICI...,Cordial saludo:_x000D_\nSres. EDIFICIO PORTO H...,Claro Empresas Colombia,/O=EXCHANGELABS/OU=EXCHANGE ADMINISTRATIVE GRO...,Coordinador de Tecnologia Porto Horizonte,[EMAIL]
1,Re: Urgente - Solicitud Cambio Asesor Comercia...,"Cordial saludo Orlando,_x000D_\n_x000D_\n _x00...",Claro Empresas Colombia,/O=EXCHANGELABS/OU=EXCHANGE ADMINISTRATIVE GRO...,Orlando Alberto Suarez Robles,/o=ExchangeLabs/ou=Exchange Administrative Gro...
2,Re: TRASLADO SERVICIOS INTELCIA,"Cordial saludo,_x000D_\n_x000D_\n _x000D_\n_x0...",Claro Empresas Colombia,/O=EXCHANGELABS/OU=EXCHANGE ADMINISTRATIVE GRO...,Diana Isela Ospina Salazar,/o=ExchangeLabs/ou=Exchange Administrative Gro...
3,RE: TRASLADO SERVICIOS INTELCIA,"Cordial saludo,_x000D_\n_x000D_\n _x000D_\n_x0...",Claro Empresas Colombia,/O=EXCHANGELABS/OU=EXCHANGE ADMINISTRATIVE GRO...,Viviana Duque Soto,/o=ExchangeLabs/ou=Exchange Administrative Gro...
4,RE: Datos servicio Hogar para traslado a cuent...,"Cordial saludo Marvic,_x000D_\n_x000D_\n _x000...",Claro Empresas Colombia,/O=EXCHANGELABS/OU=EXCHANGE ADMINISTRATIVE GRO...,Marvic Alexander Guerra Fuentes,/o=ExchangeLabs/ou=Exchange Administrative Gro...

In [21]:
ruta_salida = "/content/drive/MyDrive/KeepCoding/AI_Escalation_Assistant/escalamientos_anonimizado_final.xlsx"
df.to_excel(ruta_salida, index=False)

print("Archivo guardado correctamente")

Archivo guardado correctamente

In [22]:
df["texto_caso"] = df["Asunto"].fillna("") + " " + df["Cuerpo"].fillna("")
df[["Asunto", "texto_caso"]].head()

,Asunto,texto_caso
0,Re: Solicitud puntos Porto Horizonte / EDIFICI...,Re: Solicitud puntos Porto Horizonte / EDIFICI...
1,Re: Urgente - Solicitud Cambio Asesor Comercia...,Re: Urgente - Solicitud Cambio Asesor Comercia...
2,Re: TRASLADO SERVICIOS INTELCIA,Re: TRASLADO SERVICIOS INTELCIA Cordial saludo...
3,RE: TRASLADO SERVICIOS INTELCIA,RE: TRASLADO SERVICIOS INTELCIA Cordial saludo...
4,RE: Datos servicio Hogar para traslado a cuent...,RE: Datos servicio Hogar para traslado a cuent...

In [23]:
def clasificar_categoria(texto):
    texto = str(texto).lower()

    if "instal" in texto or "ot" in texto or "orden de trabajo" in texto:
        return "Implementación"
    elif "factura" in texto or "cobro" in texto or "nota crédito" in texto:
        return "Facturación"
    elif "caído" in texto or "falla" in texto or "indisponible" in texto:
        return "Soporte técnico"
    elif "traslado" in texto or "cambio" in texto:
        return "Traslado / Cambio"
    elif "portabilidad" in texto or "sim" in texto or "línea" in texto:
        return "Portabilidad móvil"
    else:
        return "Servicio al cliente"

df["categoria"] = df["texto_caso"].apply(clasificar_categoria)

df[["Asunto", "categoria"]].head()

0                                             Asunto       categoria
0  Re: Solicitud puntos Porto Horizonte / EDIFICI...  Implementación
1  Re: Urgente - Solicitud Cambio Asesor Comercia...  Implementación
2                    Re: TRASLADO SERVICIOS INTELCIA  Implementación
3                    RE: TRASLADO SERVICIOS INTELCIA  Implementación
4  RE: Datos servicio Hogar para traslado a cuent...  Implementación

In [24]:
df["asunto_limpio"] = df["Asunto"].str.lower().str.replace("re:", "", regex=False).str.strip()

df["numero_escalamientos"] = df.groupby("asunto_limpio")["asunto_limpio"].transform("count")

df[["Asunto", "numero_escalamientos"]].head()

0                                             Asunto  numero_escalamientos
0  Re: Solicitud puntos Porto Horizonte / EDIFICI...                     1
1  Re: Urgente - Solicitud Cambio Asesor Comercia...                     1
2                    Re: TRASLADO SERVICIOS INTELCIA                     2
3                    RE: TRASLADO SERVICIOS INTELCIA                     2
4  RE: Datos servicio Hogar para traslado a cuent...                     2

In [25]:
def asignar_prioridad(row):
    if row["numero_escalamientos"] >= 4:
        return "Alta"
    elif row["numero_escalamientos"] >= 2:
        return "Media"
    else:
        return "Baja"

df["prioridad"] = df.apply(asignar_prioridad, axis=1)

In [26]:
def asignar_semaforo(prioridad):
    if prioridad == "Alta":
        return "Rojo"
    elif prioridad == "Media":
        return "Amarillo"
    else:
        return "Verde"

df["semaforo"] = df["prioridad"].apply(asignar_semaforo)

df[["Asunto", "categoria", "numero_escalamientos", "prioridad", "semaforo"]].head()

,Asunto,categoria,numero_escalamientos,prioridad,semaforo
0,Re: Solicitud puntos Porto Horizonte / EDIFICI...,Implementación,1,Baja,Verde
1,Re: Urgente - Solicitud Cambio Asesor Comercia...,Implementación,1,Baja,Verde
2,Re: TRASLADO SERVICIOS INTELCIA,Implementación,2,Media,Amarillo
3,RE: TRASLADO SERVICIOS INTELCIA,Implementación,2,Media,Amarillo
4,RE: Datos servicio Hogar para traslado a cuent...,Implementación,2,Media,Amarillo

In [28]:
ruta_final = "/content/drive/MyDrive/KeepCoding/AI_Escalation_Assistant/escalamientos_anonimizado_final.xlsx"
df.to_excel(ruta_final, index=False)

print("Dataset final guardado correctamente")

Dataset final guardado correctamente